/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form.user;

import dao.TransaksiDAO;
import entity.Transaksi;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Willy Docksha
 */
public class Form_User extends javax.swing.JFrame {

    int bykTrans;
    String user;

    public void setUser(String user) {
        this.user = user;
    }

    public void load() {
        List<Transaksi> list = TransaksiDAO.getTransaksi();
        for (Transaksi trans : list) {
            bykTrans++;
        }
    }

    public Form_User() {
        initComponents();
        bykTrans = 0;
        load();
        lbl_transaksi_ke.setText((bykTrans + 1) + "");

        Calendar cal = Calendar.getInstance();
        SimpleDateFormat contoh = new SimpleDateFormat("EEEE, d MMMM yyyy");
        String Tanggal = contoh.format(cal.getTime());
        lbl_transaksi_tanggal.setText(Tanggal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_transaksi_tanggal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_transaksi_ke = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_transaksi_plat = new javax.swing.JTextField();
        txt_transaksi_durasi = new javax.swing.JTextField();
        txt_transaksi_biaya = new javax.swing.JTextField();
        txt_transaksi_idMember = new javax.swing.JTextField();
        txt_transaksi_NIK = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_transaksi_proses = new javax.swing.JButton();
        btn_transaksi_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Transaksi"));

        jLabel1.setText("Tanggal : ");

        lbl_transaksi_tanggal.setText("jLabel2");

        jLabel2.setText("||");

        jLabel3.setText("Transaksi ke  - ");

        lbl_transaksi_ke.setText("jLabel4");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Input"));

        jLabel4.setText("Plat Nomor : ");

        jLabel5.setText("Durasi (jam) : ");

        jLabel6.setText("Biaya : ");

        jLabel7.setText("Id Member* : ");

        jLabel8.setText("NIK* : ");

        txt_transaksi_idMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_transaksi_idMemberActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel9.setText("* jika tidak ada Id member, maka isikan dengan NIK atau NIM");

        btn_transaksi_proses.setText("Proses");
        btn_transaksi_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksi_prosesActionPerformed(evt);
            }
        });

        btn_transaksi_clear.setText("Clear");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_transaksi_proses)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_transaksi_clear))
                    .addComponent(jLabel9)
                    .addComponent(txt_transaksi_plat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_transaksi_durasi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_transaksi_biaya, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_transaksi_idMember, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_transaksi_NIK, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_transaksi_plat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_transaksi_durasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_transaksi_biaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_transaksi_idMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_transaksi_NIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_transaksi_proses)
                    .addComponent(btn_transaksi_clear))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_transaksi_tanggal)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_transaksi_ke)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_transaksi_tanggal)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lbl_transaksi_ke))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_transaksi_idMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_transaksi_idMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_transaksi_idMemberActionPerformed

    private void btn_transaksi_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksi_prosesActionPerformed
        Transaksi t = new Transaksi();
        TransaksiDAO td = new TransaksiDAO();

        String plat = txt_transaksi_plat.getText();
        String durasi = txt_transaksi_durasi.getText();
        String biaya = txt_transaksi_biaya.getText();
        String NIK = txt_transaksi_NIK.getText();
        String NIM = txt_transaksi_idMember.getText();
        String tanggal = lbl_transaksi_tanggal.getText();

        if (plat.equals("") || durasi.equals("") || biaya.equals("")) {
            JOptionPane.showMessageDialog(this, "Inputan harus sesuai");
        } else if (!NIK.equals("") && !NIM.equals("")) {
            JOptionPane.showMessageDialog(this, "Input 1 ID transaksi saja");
        } else {
            t.setDurasi(durasi);
            t.setTanggal(tanggal);
            t.setJam(durasi);
            t.setNIK(NIK);
            t.setId_member(NIM);
            t.setId_transaksi("Trans" + bykTrans);
            t.setId_user(user);
            t.setPlat_nomor(plat);
            t.setBiaya(biaya); // aslinya bukan inputan, tapi otomatis
            td.insert(t);
            JOptionPane.showMessageDialog(this, "Data Berhasil disimpan");
            clear();
        }

        /*
         
         if(text_pwd.getText().toString().equals(text_repwd.getText().toString()))
         {
         p.setId_user(textID);
         p.setNama(textNama);
         p.setPasword(textPWD);
         p.setAlamat(textAlamat);
         p.setTelp(textTlp);
         p.setEmail(email);
         pd.insert(p);
         dispose();
         }
         else
         {
         JOptionPane.showMessageDialog(null, "Password tidak match !!!!");
         }
         */
    }//GEN-LAST:event_btn_transaksi_prosesActionPerformed

    void clear() {
        txt_transaksi_NIK.setText("");
        txt_transaksi_biaya.setText("");
        txt_transaksi_durasi.setText("");
        txt_transaksi_idMember.setText("");
        txt_transaksi_plat.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_transaksi_clear;
    private javax.swing.JButton btn_transaksi_proses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_transaksi_ke;
    private javax.swing.JLabel lbl_transaksi_tanggal;
    private javax.swing.JTextField txt_transaksi_NIK;
    private javax.swing.JTextField txt_transaksi_biaya;
    private javax.swing.JTextField txt_transaksi_durasi;
    private javax.swing.JTextField txt_transaksi_idMember;
    private javax.swing.JTextField txt_transaksi_plat;
    // End of variables declaration//GEN-END:variables
}
