/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form.admin;

import com.sun.glass.events.MouseEvent;
import dao.AddDataMemberDAO;
import dao.ListMobilDAO;
import dao.UserDAO;
import dao.list_mobil;
import entity.JenisMobil;
import entity.Member;
import entity.Users;
import entity.listmobil;
import java.awt.Panel;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.accessibility.AccessibleAction;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Willy Docksha
 */
public class Form_Admin extends javax.swing.JFrame {

    public Form_Admin() {
        initComponents();
        showDataMember();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu5 = new java.awt.Menu();
        menu6 = new java.awt.Menu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        button_data_member_add = new javax.swing.JButton();
        button_data_member_update = new javax.swing.JButton();
        button_data_member_delete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        button_data_jenismobil_add = new javax.swing.JButton();
        button_data_jenismobil_update = new javax.swing.JButton();
        button_data_jenismobil_delete = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        button_data_listmobil_add = new javax.swing.JButton();
        button_data_listmobil_update = new javax.swing.JButton();
        button_data_listmobil_delete = new javax.swing.JButton();
        button_data_listmobil_add1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        button_data_user_add = new javax.swing.JButton();
        button_data_user_delete = new javax.swing.JButton();
        button_data_user_update = new javax.swing.JButton();
        button_data_user_add1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        menu5.setLabel("File");
        menuBar3.add(menu5);

        menu6.setLabel("Edit");
        menuBar3.add(menu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Search : ");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Member", "Nama", "Alamat", "Jenis Kelamin", "Nomor Identitas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        button_data_member_add.setText("Add Data");
        button_data_member_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_data_member_addMouseClicked(evt);
            }
        });
        button_data_member_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_data_member_addActionPerformed(evt);
            }
        });

        button_data_member_update.setText("Update Data");
        button_data_member_update.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                button_data_member_updateStateChanged(evt);
            }
        });
        button_data_member_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_data_member_updateMouseClicked(evt);
            }
        });
        button_data_member_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_data_member_updateActionPerformed(evt);
            }
        });

        button_data_member_delete.setText("Delete Data");
        button_data_member_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_data_member_deleteMouseClicked(evt);
            }
        });
        button_data_member_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_data_member_deleteActionPerformed(evt);
            }
        });

        jButton1.setText("referesh");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_data_member_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_data_member_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_data_member_delete)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_data_member_add)
                    .addComponent(button_data_member_delete)
                    .addComponent(button_data_member_update)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Member", jPanel2);

        jLabel3.setText("Search : ");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Jenis Mobil", "Merk", "Nama Mobil", "Harga", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        button_data_jenismobil_add.setText("Add Data");
        button_data_jenismobil_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_data_jenismobil_addMouseClicked(evt);
            }
        });
        button_data_jenismobil_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_data_jenismobil_addActionPerformed(evt);
            }
        });

        button_data_jenismobil_update.setText("Update Data");

        button_data_jenismobil_delete.setText("Delete Data");

        jButton2.setText("refresh");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_data_jenismobil_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_data_jenismobil_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_data_jenismobil_delete)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_data_jenismobil_add)
                    .addComponent(button_data_jenismobil_delete)
                    .addComponent(button_data_jenismobil_update)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Jenis Mobil", jPanel3);

        jLabel4.setText("Search : ");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Plat Nomor", "Id Jenis Mobil", "Jumlah Kursi", "Warna"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        button_data_listmobil_add.setText("Add Data");
        button_data_listmobil_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_data_listmobil_addMouseClicked(evt);
            }
        });

        button_data_listmobil_update.setText("Update Data");

        button_data_listmobil_delete.setText("Delete Data");
        button_data_listmobil_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_data_listmobil_deleteMouseClicked(evt);
            }
        });

        button_data_listmobil_add1.setText("Refresh");
        button_data_listmobil_add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_data_listmobil_add1MouseClicked(evt);
            }
        });
        button_data_listmobil_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_data_listmobil_add1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(button_data_listmobil_add1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_data_listmobil_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_data_listmobil_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_data_listmobil_delete)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_data_listmobil_add)
                    .addComponent(button_data_listmobil_delete)
                    .addComponent(button_data_listmobil_update)
                    .addComponent(button_data_listmobil_add1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data List mobil", jPanel4);

        jLabel1.setText("Search : ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id User", "Nama", "Password", "Alamat", "Nomor Telp", "E-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        button_data_user_add.setText("Add Data");
        button_data_user_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_data_user_addMouseClicked(evt);
            }
        });
        button_data_user_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_data_user_addActionPerformed(evt);
            }
        });

        button_data_user_delete.setText("Delete Data");
        button_data_user_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_data_user_deleteMouseClicked(evt);
            }
        });

        button_data_user_update.setText("Update Data");

        button_data_user_add1.setText("Refresh");
        button_data_user_add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_data_user_add1MouseClicked(evt);
            }
        });
        button_data_user_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_data_user_add1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(button_data_user_add1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_data_user_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_data_user_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_data_user_delete)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_data_user_add)
                    .addComponent(button_data_user_delete)
                    .addComponent(button_data_user_update)
                    .addComponent(button_data_user_add1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data User", jPanel1);

        jMenu1.setText("File");

        jMenu3.setText("Logout");
        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        About a = new About(this, rootPaneCheckingEnabled);
        a.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void button_data_user_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_data_user_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_data_user_addActionPerformed

    private void button_data_member_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_data_member_addMouseClicked
        Form.JDialogMember member = new Form.JDialogMember(this, rootPaneCheckingEnabled);
        member.setBtn("Add");
        member.setVisible(true);
    }//GEN-LAST:event_button_data_member_addMouseClicked

    private void button_data_member_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_data_member_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_data_member_addActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        showDataMember();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void button_data_member_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_data_member_updateActionPerformed
        Form.JDialogMember update = new Form.JDialogMember(this, rootPaneCheckingEnabled);
        update.setBtn("Update");
        String id = jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString();
        String nama = jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString();
        String alamat = jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString();
        String identitas = jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString();

        Long idbesar = 0L;
        List<Member> list = AddDataMemberDAO.getAddMember();
        for (Member member : list) {
            String cekId = member.getId_member().toString();
            String cekNama = "s";

            if (cekId.equals(id) && cekNama.equals(nama)) {
                idbesar = member.getId();
                break;
            }
        }

        update.setData(id, nama, alamat, identitas, idbesar);
        update.setVisible(true);
    }//GEN-LAST:event_button_data_member_updateActionPerformed

    private void button_data_member_updateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_button_data_member_updateStateChanged

    }//GEN-LAST:event_button_data_member_updateStateChanged

    private void button_data_member_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_data_member_updateMouseClicked
        //showDataUpdate();
    }//GEN-LAST:event_button_data_member_updateMouseClicked

    private void button_data_jenismobil_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_data_jenismobil_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_data_jenismobil_addActionPerformed

    private void button_data_jenismobil_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_data_jenismobil_addMouseClicked
        Form.JDialogJenisMobil jenismobil = new Form.JDialogJenisMobil(this, rootPaneCheckingEnabled);
        jenismobil.setBtn("Add");
        jenismobil.setVisible(true);
    }//GEN-LAST:event_button_data_jenismobil_addMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        showDataJenisMobil();
    }//GEN-LAST:event_jButton2MouseClicked

    private void showDataListMobil() {
        try {
            List<listmobil> list = list_mobil.GetlistMobil();
            Object data[][] = new Object[list.size()][4];
            int i = 0;
            for (listmobil listMember : list) {
                data[i][0] = listMember.getPlatnomer();
                data[i][1] = listMember.getId();
                data[i][2] = listMember.getJumlahkursi();
                data[i][3] = listMember.getWarna();
                i++;
            }
            String header[] = {"Plat Nomer", "Id Jenis Mobil", "Jumlah Kursi", "warna"};
            jTable4.setModel(new DefaultTableModel(data, header));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void showDataJenisMobil() {
//
//        try {
//            //List<JenisMobil> list = ListMobilDAO.getListMobil();
//            List<JenisMobil> list = ListMobilDAO.getListMobil();
//            Object data[][] = new Object[list.size()][5];
//            int i = 0;
//            for (JenisMobil listMember : list) {
//                data[i][0] = listMember.getId();
//                data[i][1] = listMember.getNamaMobil();
//                data[i][2] = listMember.getMerek();
//                int harga = listMember.getHarga();
//                data[i][3] = harga;
//                data[i][4] = listMember.getKet();
//                i++;
//            }
//            String header[] = {"ID Mobil", "Nama Mobil", "Merek", "Harga", "Keterangan"};
//            jTable3.setModel(new DefaultTableModel(data, header));
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }

    private void button_data_listmobil_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_data_listmobil_addMouseClicked
        Form.JDialogListMobil listmobil = new Form.JDialogListMobil(this, rootPaneCheckingEnabled);
        listmobil.setBtn("Add");
        listmobil.setVisible(true);
    }//GEN-LAST:event_button_data_listmobil_addMouseClicked

    private void button_data_user_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_data_user_addMouseClicked
        Form.JDialogUser users = new Form.JDialogUser(this, rootPaneCheckingEnabled);
        users.setBtn("Add");
        users.setVisible(true);
    }//GEN-LAST:event_button_data_user_addMouseClicked

    private void button_data_listmobil_add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_data_listmobil_add1MouseClicked
        showDataListMobil();
    }//GEN-LAST:event_button_data_listmobil_add1MouseClicked

    private void button_data_listmobil_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_data_listmobil_add1ActionPerformed

    }//GEN-LAST:event_button_data_listmobil_add1ActionPerformed

    private void button_data_user_add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_data_user_add1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_data_user_add1MouseClicked

    private void button_data_user_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_data_user_add1ActionPerformed
        showDataUser();
    }//GEN-LAST:event_button_data_user_add1ActionPerformed

    private void button_data_listmobil_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_data_listmobil_deleteMouseClicked
        String plat_nomor = jTable4.getValueAt(jTable4.getSelectedRow(), 0).toString();
        String id_jenis_nomor = jTable4.getValueAt(jTable4.getSelectedRow(), 1).toString();
        String jumlah_kursi = jTable4.getValueAt(jTable4.getSelectedRow(), 2).toString();
        String warna = jTable4.getValueAt(jTable4.getSelectedRow(), 3).toString();

        String tampung = "";

        List<listmobil> list = list_mobil.GetlistMobil();
        for (listmobil mobil : list) {
            String cekId = mobil.getId().toString(),
                    cekPlat = mobil.getPlatnomer().toString(),
                    //cekIdJenis = mobil.get().toString(),
                    cekJumlah_kursi = mobil.getJumlahkursi().toString(),
                    cekWarna = mobil.getWarna().toString();
            if (plat_nomor.equals(cekPlat) && jumlah_kursi.equals(cekJumlah_kursi) && warna.equals(cekWarna)) {
                tampung = cekId;
                break;
            }
        }

        JenisMobil lm = new JenisMobil();
        //listmobil lm = new listmobil();
        ListMobilDAO l_m = new ListMobilDAO();
        if (!tampung.equals("")) {
            lm.setId(Long.parseLong(tampung));
//            l_m.delete(lm);
        }

    }//GEN-LAST:event_button_data_listmobil_deleteMouseClicked

    private void button_data_user_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_data_user_deleteMouseClicked
        String id_user = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String nama = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String password = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String alamat = jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
        String telp = jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
        String email = jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString();

        System.out.println(id_user + " || " + nama + " || " + password + " || " + alamat + " || " + telp + " || " + email);
        String tampung = "";

        List<Users> list = UserDAO.getPersons();
        for (Users user : list) {
            String cekId = user.getId().toString(),
                    cekAlamat = user.getAlamat().toString(),
                    cekEmail = user.getEmail().toString(),
                    cekIduser = user.getId_user().toString(),
                    cekNama = user.getNama().toString(),
                    cekPassword = user.getPasword().toString(),
                    cekTelp = user.getTelp().toString();
            System.out.println(cekIduser+" || "+cekNama+" || "+cekPassword+" || "+cekAlamat+" || "+cekTelp+" || "+cekEmail);
            if (id_user.equals(cekIduser)
                    && nama.equals(cekNama)
                    && password.equals(cekPassword)
                    && alamat.equals(cekAlamat)
                    && telp.equals(cekTelp)
                    && email.equals(cekEmail)) {
                tampung = cekId;
                System.out.println("tampungtampung  " + tampung);
                break;
            }
        }

        Users u = new Users();
        UserDAO ud = new UserDAO();
        if (!tampung.equals("")) {
            u.setId(Long.parseLong(tampung));
            ud.delete(u);
            JOptionPane.showMessageDialog(this, "Berhasil di Hapus");
        } else {
            JOptionPane.showMessageDialog(this, "Tidak berhasil dihapus");
        }
        
        showDataUser();
    }//GEN-LAST:event_button_data_user_deleteMouseClicked

    private void button_data_member_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_data_member_deleteActionPerformed
        String id_user = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String nama = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String alamat = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String gender = jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
        String idetitas = jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();

        String tampung = "";

        List<Member> list = AddDataMemberDAO.getAddMember();
        for (Member member : list) {
            String cekId = member.getId().toString(),
                    cekAlamat = member.getAlamat().toString(),
                    cekIduser = member.getId_member().toString(),
                    cekJK = member.getJenis_kelamin().toString(),
                    cekNama = member.getNama().toString();
            if (id_user.equals(cekIduser)
                    && nama.equals(cekNama)
                    && alamat.equals(cekAlamat)
                    && gender.equals(cekJK)) {
                tampung = cekId;
                break;
            }
        }

        Member u = new Member();
        AddDataMemberDAO ud = new AddDataMemberDAO();
        if (!tampung.equals("")) {
            u.setId(Long.parseLong(tampung));
            ud.delete(u);
        }
    }//GEN-LAST:event_button_data_member_deleteActionPerformed

    private void button_data_member_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_data_member_deleteMouseClicked
        String id_user = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String nama = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String password = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String alamat = jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
        String telp = jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
        String email = jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString();

        String tampung = "";

        List<Users> list = UserDAO.getPersons();
        for (Users user : list) {
            String cekId = user.getId().toString(),
                    cekAlamat = user.getAlamat().toString(),
                    cekEmail = user.getEmail().toString(),
                    cekIduser = user.getId_user().toString(),
                    cekNama = user.getNama().toString(),
                    cekPassword = user.getPasword().toString(),
                    cekTelp = user.getTelp().toString();
            if (id_user.equals(cekIduser)
                    && nama.equals(cekNama)
                    && password.equals(cekPassword)
                    && alamat.equals(cekAlamat)
                    && telp.equals(cekAlamat)
                    && email.equals(cekEmail)) {
                tampung = cekId;
                break;
            }
        }

        Users u = new Users();
        UserDAO ud = new UserDAO();
        if (!tampung.equals("")) {
            u.setId(Long.parseLong(tampung));
            ud.delete(u);
        }
    }//GEN-LAST:event_button_data_member_deleteMouseClicked

    private void showDataUpdate() {
        try {
            String id = jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString();
            String nama = jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString();
            String alamat = jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString();
            String gender = jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString();
            String identitas = jTable2.getValueAt(jTable2.getSelectedRow(), 4).toString();
            Long idbesar = 0L;
            List<Member> list = AddDataMemberDAO.getAddMember();
            for (Member member : list) {
                String cekId = member.getId_member().toString();
                String cekNama = "s";

                if (cekId.equals(id) && cekNama.equals(nama)) {
                    idbesar = member.getId();
                    break;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void showDataMember() {

        try {
            List<Member> list = AddDataMemberDAO.getAddMember();
            Object data[][] = new Object[list.size()][5];
            int i = 0;
            for (Member listMember : list) {
                data[i][0] = listMember.getId_member();
                data[i][1] = listMember.getNama();
                data[i][2] = listMember.getAlamat();
                data[i][3] = listMember.getJenis_kelamin();
                data[i][4] = listMember.getNomor_identitas();
                i++;
            }
            String header[] = {"ID Member", "Nama", "Alamat", "Jenis Kelamin", "Nomer Identitas :"};
            jTable2.setModel(new DefaultTableModel(data, header));

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void showDataUser() {

        try {
            List<Users> list = UserDAO.getPersons();
            Object data[][] = new Object[list.size()][6];
            int i = 0;
            for (Users listMember : list) {
                data[i][0] = listMember.getId_user();
                data[i][1] = listMember.getNama();
                data[i][2] = listMember.getPasword();
                data[i][3] = listMember.getAlamat();
                data[i][4] = listMember.getTelp();
                data[i][5] = listMember.getEmail();
                i++;
            }
            String header[] = {"ID User", "Nama ", "Pasword", "Alamat", "Telepon ", "Email"};
            jTable1.setModel(new DefaultTableModel(data, header));

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_data_jenismobil_add;
    private javax.swing.JButton button_data_jenismobil_delete;
    private javax.swing.JButton button_data_jenismobil_update;
    private javax.swing.JButton button_data_listmobil_add;
    private javax.swing.JButton button_data_listmobil_add1;
    private javax.swing.JButton button_data_listmobil_delete;
    private javax.swing.JButton button_data_listmobil_update;
    private javax.swing.JButton button_data_member_add;
    private javax.swing.JButton button_data_member_delete;
    private javax.swing.JButton button_data_member_update;
    private javax.swing.JButton button_data_user_add;
    private javax.swing.JButton button_data_user_add1;
    private javax.swing.JButton button_data_user_delete;
    private javax.swing.JButton button_data_user_update;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.Menu menu6;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    // End of variables declaration//GEN-END:variables
}
